#!/usr/bin/env node
/* Emits a block-scoped Geist type scale.
 *
 * Values are transcribed from the compiled CSS that vercel.com/geist/typography
 * ships — not re-derived. Font families are indirected through the project's
 * own --font-sans / --font-mono rather than Geist's, per project decision. */

const SANS = "var(--font-sans, ui-sans-serif, system-ui, sans-serif)";
const MONO = "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)";

/* [name, size, line-height, tracking|null, mono] */
const SCALES = {
  heading: {
    weight: 600,
    /* <strong> inside a heading is Geist's "Subtle" modifier: it de-emphasizes. */
    strong: { weight: 500, color: "var(--gray-text-low, currentColor)", only: [20, 24, 32] },
    tokens: [
      ["heading-72", 72, 72, -4.32, false],
      ["heading-64", 64, 64, -3.84, false],
      ["heading-56", 56, 56, -3.36, false],
      ["heading-48", 48, 56, -2.88, false],
      ["heading-40", 40, 48, -2.4, false],
      ["heading-32", 32, 40, -1.28, false],
      ["heading-24", 24, 32, -0.96, false],
      ["heading-20", 20, 26, -0.4, false],
      ["heading-16", 16, 24, -0.32, false],
      ["heading-14", 14, 20, -0.28, false],
    ],
  },
  copy: {
    weight: 400,
    strong: { weight: 550, color: "var(--gray-text-high, currentColor)" },
    tokens: [
      ["copy-24", 24, 36, null, false],
      ["copy-20", 20, 36, null, false],
      ["copy-18", 18, 28, null, false],
      ["copy-16", 16, 24, null, false],
      ["copy-14", 14, 20, null, false],
      ["copy-14-mono", 14, 20, null, true],
      ["copy-13", 13, 18, null, false],
      ["copy-13-mono", 13, 18, null, true],
    ],
  },
  label: {
    weight: 400,
    strong: { weight: 500, color: "var(--gray-text-high, currentColor)" },
    tokens: [
      ["label-20", 20, 32, null, false],
      ["label-18", 18, 20, null, false],
      ["label-16", 16, 20, null, false],
      ["label-14", 14, 20, null, false],
      ["label-14-mono", 14, 20, null, true],
      ["label-13", 13, 16, null, false],
      ["label-13-mono", 13, 20, null, true],
      ["label-12", 12, 16, null, false],
      ["label-12-mono", 12, 16, null, true],
    ],
  },
  button: {
    weight: 500,
    strong: null,
    tokens: [
      ["button-16", 16, 20, null, false],
      ["button-14", 14, 20, null, false],
      ["button-12", 12, 16, null, false],
    ],
  },
};

const argv = process.argv.slice(2);
const block = argv.find((a) => !a.startsWith("--"));
if (!block) {
  console.error("usage: build-type.mjs <block-name> [--include heading,copy,label,button] [--no-mono]");
  process.exit(1);
}
const includeArg = argv.indexOf("--include");
const include =
  includeArg === -1
    ? Object.keys(SCALES)
    : argv[includeArg + 1].split(",").map((s) => s.trim());
const noMono = argv.includes("--no-mono");

for (const name of include) {
  if (!SCALES[name]) {
    console.error(`unknown scale "${name}" — expected one of: ${Object.keys(SCALES).join(", ")}`);
    process.exit(1);
  }
}

const rule = (sel, decls) => `${sel} {\n${decls.map((d) => `  ${d}`).join("\n")}\n}`;

const out = [];
out.push(`/* Type scale: Geist, block-scoped to .${block}`);
out.push(` * Generated by .claude/skills/type-scale`);
out.push(` * Regenerate: node .claude/skills/type-scale/scripts/build-type.mjs ${argv.join(" ")}`);
out.push(` *`);
out.push(` * Metrics are Geist's. Families resolve to this project's --font-sans /`);
out.push(` * --font-mono, so the scale inherits whatever face the app already loads. */`);
out.push("");

const report = [];

for (const name of include) {
  const scale = SCALES[name];
  const tokens = scale.tokens.filter((t) => !(noMono && t[4]));
  if (!tokens.length) continue;

  out.push(`/* ${name} — weight ${scale.weight} */`);
  for (const [token, size, leading, tracking, mono] of tokens) {
    const decls = [
      `font-family: ${mono ? MONO : SANS};`,
      `font-size: ${size}px;`,
      `line-height: ${leading}px;`,
      `font-weight: ${scale.weight};`,
    ];
    if (tracking !== null) decls.push(`letter-spacing: ${tracking}px;`);
    out.push(rule(`.${block} .type-${token}`, decls));

    const s = scale.strong;
    if (s && (!s.only || s.only.includes(size))) {
      out.push(
        rule(`.${block} .type-${token} > strong`, [
          `font-weight: ${s.weight};`,
          `color: ${s.color};`,
        ])
      );
    }
    report.push({ scale: name, token, size, leading, tracking, mono });
  }
  out.push("");
}

process.stdout.write(out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n");

/* --- report ------------------------------------------------------------- */
const err = [];
err.push("");
err.push(`Type scale report — .${block}`);
err.push("  token             size  leading  ratio   tracking  family");
for (const t of report) {
  const ratio = (t.leading / t.size).toFixed(2);
  err.push(
    `  ${t.token.padEnd(16)}  ${String(t.size).padStart(3)}px  ${String(t.leading).padStart(4)}px  ${ratio.padStart(5)}   ` +
      `${(t.tracking === null ? "—" : `${t.tracking}px`).padStart(8)}  ${t.mono ? "mono" : "sans"}`
  );
}

const tight = report.filter((t) => t.leading / t.size < 1.25 && t.size <= 20);
if (tight.length) {
  err.push("");
  err.push("  note: single-line only — leading is too tight to wrap:");
  for (const t of tight) err.push(`    .type-${t.token} (${(t.leading / t.size).toFixed(2)})`);
}
err.push("");
err.push(`  ${report.length} tokens. Tracking is applied to headings only; Geist sets none`);
err.push("  on copy, label or button.");
err.push("");
process.stderr.write(err.join("\n"));
