import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Figtree,
  Instrument_Serif,
  Inter,
  Newsreader,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DialRoot } from "dialkit";
import "dialkit/styles.css";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

/* Display serif. Used for the italic accents inside the hero-split
 * headline chips and for the numerals in its dashboard mock — both need
 * a face with real italic drawing, which the sans does not have. */
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* Harvey block fonts — consumed by sections/HarveyAI/harvey.css as
 * --harvey-font-sans / --harvey-font-serif (the *-src variables live on <body>,
 * so harvey.css resolves them on .harvey, not :root). Newsreader carries an optical-size
 * axis and true italics, so it holds up in both headlines and body copy. */
const HarveySansFont = Inter({
  subsets: ["latin"],
  variable: "--harvey-sans-src",
});

const HarveySerifFont = Newsreader({
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz"],
  variable: "--harvey-serif-src",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", figtree.variable, instrumentSerif.variable)}
    >
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          HarveySansFont.variable,
          HarveySerifFont.variable,
          "antialiased",
        )}
      >
        <main className="bg-background text-foreground">
          {children}
          <DialRoot />
        </main>
      </body>
    </html>
  );
}
